// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqN2SmhQgWjyvnpcBC9xfRXYVk6C1ews',
    appId: '1:301935249856:web:3bb72540903e75b7516025',
    messagingSenderId: '301935249856',
    projectId: 'fir-testing-38490',
    authDomain: 'fir-testing-38490.firebaseapp.com',
    storageBucket: 'fir-testing-38490.firebasestorage.app',
    measurementId: 'G-G0KL8RPX3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVLEFt64EBCWe5dbRFoL33EI5jJNoYlSg',
    appId: '1:301935249856:android:72380d5641a413c3516025',
    messagingSenderId: '301935249856',
    projectId: 'fir-testing-38490',
    storageBucket: 'fir-testing-38490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0eUpiZi57QloK4QUoU6jsrknzVgBB2r0',
    appId: '1:301935249856:ios:f8d25cce904c062d516025',
    messagingSenderId: '301935249856',
    projectId: 'fir-testing-38490',
    storageBucket: 'fir-testing-38490.firebasestorage.app',
    iosBundleId: 'com.example.appfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0eUpiZi57QloK4QUoU6jsrknzVgBB2r0',
    appId: '1:301935249856:ios:f8d25cce904c062d516025',
    messagingSenderId: '301935249856',
    projectId: 'fir-testing-38490',
    storageBucket: 'fir-testing-38490.firebasestorage.app',
    iosBundleId: 'com.example.appfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqN2SmhQgWjyvnpcBC9xfRXYVk6C1ews',
    appId: '1:301935249856:web:4ab7b36760e2403e516025',
    messagingSenderId: '301935249856',
    projectId: 'fir-testing-38490',
    authDomain: 'fir-testing-38490.firebaseapp.com',
    storageBucket: 'fir-testing-38490.firebasestorage.app',
    measurementId: 'G-7Y5V5DHZVR',
  );
}
